In [1]:
import numpy as np #importamos numpy

In [2]:
lista = [1,2,3] # creamos una lista
array = np.array(lista) # creamos un array

In [3]:
array # imprimimos el array

array([1, 2, 3])

In [4]:
array.shape # imprimimos el tamaño del array

(3,)

In [5]:
np.arange(0,21,2) # creamos un array con valores de 0 a 20 con paso de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
np.zeros(shape=(10,4)) # creamos un array de 10x4 con valores 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones(shape=(10,3)) # creamos un array de 10x4 con valores 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
aleatorios= np.random.randint(0,100,50)

In [9]:
aleatorios # imprimimos el array

array([64, 70,  2, 18, 29, 48, 93, 98, 69, 26, 94, 24, 51, 26, 42, 99,  6,
       75, 40, 68, 78, 76, 40,  7, 72, 90, 62,  4,  8, 81, 96, 48, 79, 57,
       37, 41, 39, 62, 37,  7,  5, 18, 88, 16, 54, 15, 44, 33, 37, 75])

In [10]:
aleatorios.argmax() # imprimimos el indice del valor mas alto

15

In [11]:
aleatorios.max() # imprimimos el valor mas alto

99

In [12]:
aleatorios.min() # imprimimos el valor mas bajo

2

In [13]:
aleatorios.argmin()

2

In [14]:
aleatorios.shape # imprimimos el tamaño del array

(50,)

In [15]:
aleatorios=aleatorios.reshape(10,5) # cambiamos el tamaño del array

In [16]:
aleatorios

array([[64, 70,  2, 18, 29],
       [48, 93, 98, 69, 26],
       [94, 24, 51, 26, 42],
       [99,  6, 75, 40, 68],
       [78, 76, 40,  7, 72],
       [90, 62,  4,  8, 81],
       [96, 48, 79, 57, 37],
       [41, 39, 62, 37,  7],
       [ 5, 18, 88, 16, 54],
       [15, 44, 33, 37, 75]])

In [17]:
aleatorios[0,0] # imprimimos el valor en la posicion 0,0

64

In [18]:
aleatorios[1,0] # imprimimos el valor en la posicion 1,0

48